/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_suirui_test_JniTest */

#ifndef _Included_org_suirui_test_JniTest
#define _Included_org_suirui_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
